py: Use smart holder for `Camera` if available
The `Camera` class has a private destructor, so `std::shared_ptr<>` cannot
be used as a holder type. In recent versions of pybind11, the custom holder
type that was used no longer works:

  RuntimeError: Unable to convert std::shared_ptr<T> to Python when the bound
  type does not use std::shared_ptr or py::smart_holder as its holder type

This appears to be intentional and the fact that it worked is accidental.

Fix that by using a "smart holder" since pybind11 3.x, and falling back to
the custom one in previous versions.

Link: https://github.com/pybind/pybind11/issues/6064
Closes: https://gitlab.freedesktop.org/camera/libcamera/-/work_items/334
Signed-off-by: Barnabás Pőcze <barnabas.pocze@ideasonboard.com>
Reviewed-by: Tomi Valkeinen <tomi.valkeinen@ideasonboard.com>
Reviewed-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>